---
dependency:
  name: galaxy
lint:
  name: yamllint
platforms:
  - name: local
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      connection: local
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: server
verifier:
  name: testinfra
  lint:
    name: flake8
