---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: local
provisioner:
  name: delegated
  ansible_connection_options:
    connection: local
  lint:
    name: ansible-lint
scenario:
  name: server
verifier:
  name: testinfra
  lint:
    name: flake8
