# vim: ts=2 sw=2 et :
---
language: python

rvm:
  - 2.4.1

dist: xenial

sudo: required

services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - molecule test -s default && molecule test -s server

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
