# vim: ts=2 sw=2 et :
---
language: python

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-pip

services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - molecule test -s default && molecule test -s server

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
