---
- src: nephelaiio.rabbitmq
  version: 1.0.2
- src: DavidWittman.redis
  version: 1.2.4
- src: nephelaiio.rbenv
  version: 1.0.11
- src: franklinkim.users
  version: 1.8.0
- src: tumf.systemd-service
  version: 1.9
