---
- src: nephelaiio.rabbitmq
  version: 1.0.2
- src: geerlingguy.redis
  version: 1.5.1
- src: nephelaiio.rbenv
  version: 1.0.11
- src: franklinkim.users
  version: 1.8.0
- src: tumf.systemd-service
  version: 1.9
