---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true
  tags:
    - sensu

- name: install apt key
  become: yes
  changed_when: false
  apt_key:
    url: https://sensu.global.ssl.fastly.net/apt/pubkey.gpg
    repo: "https://sensu.global.ssl.fastly.net/apt {{ ansible_distribution_release }} main"
  when: ansible_os_family == 'Debian'

- name: install apt repo
  become: yes
  apt_repository:
    filename: sensu
    repo: "https://sensu.global.ssl.fastly.net/apt {{ ansible_distribution_release }} main"
  when: ansible_os_family == 'Debian'

- name: install yum repo
  become: yes
  yum_repository:
    filename: sensu
    baseurl: "https://sensu.global.ssl.fastly.net/yum/$releasever/$basearch/"
  when: ansible_os_family == 'RedHat'

- name: install sensu packages
  become: yes
  package:
    name: "{{ item }}"
    state: "{{ sensu_package_state }}"
  with_items: "{{ sensu_package_names }}"

# - name: configure sensu
#   become: yes
#   template:
#     src: "{{ sensu_conf_template }}"
#     dest: "{{ sensu_conf_path }}"
#   notify:
#     - restart sensu
#
# - name: manage sensu services
#   become: yes
#   service:
#     name: "{{ item }}"
#     state: "{{ sensu_service_status }}"
#   with_items: "{{ sensu_service_names }}"
