---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true
  tags:
    - sensu

- name: install dependencies
  become: yes
  package: 
    name: apt-transport-https
  when: ansible_os_family == 'Debian'
    
- name: install apt key
  become: yes
  changed_when: false
  apt_key:
    url: https://sensu.global.ssl.fastly.net/apt/pubkey.gpg
  when: ansible_os_family == 'Debian'

- name: install apt repo
  become: yes
  apt_repository:
    filename: sensu
    repo: "deb https://sensu.global.ssl.fastly.net/apt {{ ansible_distribution_release }} main"
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: install yum repo
  become: yes
  yum_repository:
    name: sensu
    description: sensu app repository
    baseurl: "https://sensu.global.ssl.fastly.net/yum/$releasever/$basearch/"
    gpgcheck: 0
  when: ansible_os_family == 'RedHat'

- name: install packages
  become: yes
  package:
    name: "{{ item }}"
    state: "{{ sensu_package_state }}"
  with_items: "{{ sensu_package_names }}"

- name: create configuration directories
  become: yes
  file:
    path: "{{ item | dirname }}"
    state: directory
  with_items: "{{ sensu_conf_files }}"

- name: manage configuration packages
  become: yes
  template:
    src: "{{ item | basename }}.j2"
    dest: "{{ item }}"
  with_items: "{{ sensu_conf_files }}"
  notify:
    - restart sensu

- name: manage services
  become: yes
  service:
    name: "{{ item }}"
    state: "{{ sensu_service_status }}"
    enabled: "{{ sensu_service_enabled }}"
  with_items: "{{ sensu_service_names }}"
