---
- name: reload systemd
  command: systemctl daemon-reload
  tags:
    - skip_ansible_lint

- name: restart client service
  systemd:
    name: sensu-client
    state: restarted
  when: not sensu_server

- name: restart master service
  systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - sensu-api
    - sensu-server
  when: sensu_server
